// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ9phaNkSs54cRo_YvFMAa3NL6fs0vRSE',
    appId: '1:601057492767:web:a532d0118f0fd4e84cfa2a',
    messagingSenderId: '601057492767',
    projectId: 'jg-account-book',
    authDomain: 'jg-account-book.firebaseapp.com',
    storageBucket: 'jg-account-book.firebasestorage.app',
    measurementId: 'G-0DL90QNJZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDffvLkCv4rfrmHBsJUe5wR_3nC9kB4gWk',
    appId: '1:601057492767:android:d9447de27c91c5b54cfa2a',
    messagingSenderId: '601057492767',
    projectId: 'jg-account-book',
    storageBucket: 'jg-account-book.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIoEL46l9-MEaaIoB62xjgt_IcGTwRYuA',
    appId: '1:601057492767:ios:8e6eb8e777dfdbc14cfa2a',
    messagingSenderId: '601057492767',
    projectId: 'jg-account-book',
    storageBucket: 'jg-account-book.firebasestorage.app',
    iosBundleId: 'com.example.jgAccountBook.RunnerTests',
  );
}
